---
title: "Entrega 4"
author: "Ángel García, Arnau Piferrer y Guillem Serra"
format: html
editor: visual
---

Este es el [repositorio](https://github.com/GSMir/Entrega4) de GitHub en el que alojaremos todos los archivos relacionados con esta entrega.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<!--- Para las librerías --->

```{r, message = FALSE,warning=FALSE}
library(tidyverse)
library(readxl)
library(dplyr)
```

<!--- Carga de los datos --->

```{r}
gorrionesS = read_xlsx("gorriones.xlsx", sheet = "Supervivientes")
gorrionesN = read_xlsx("gorriones.xlsx", sheet = "No supervivientes")
```

```{r}
gorrionesS = gorrionesS %>%
  rename(tlen = X1, eala = X2, picolen = X3, humlen = X4, estlen = X5)
S = rep(1,28)
gorrionesS$superv <- factor(S)
gorrionesS <- gorrionesS %>%
  select(superv, tlen, eala, picolen, humlen, estlen)


gorrionesN = gorrionesN %>%
  rename(tlen = X1_1, eala = X2_2, picolen = X3_3, humlen = X4_4, estlen = X5_5)
N = numeric(21)
gorrionesN$superv <- factor(N)
gorrionesN <- gorrionesN %>%
  select(superv, tlen, eala, picolen, humlen, estlen)


gorriones = rbind(gorrionesS, gorrionesN)
```

<!--- Y aquí finalmente lo que nos pide el ejercicio --->


<!---```{r}

```
--->

